name: flutter_background
description: A plugin to keep flutter apps running in the background.
version: 1.3.0
repository: https://github.com/JulianAssmann/flutter_background
homepage: https://julianassmann.de/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: de.julianassmann.flutter_background
        pluginClass: FlutterBackgroundPlugin
